apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlflow
resources:
  - certificate.yaml
  - source.yaml
  - release.yaml
  - release-nginx.yaml
  - volumes.yaml
configMapGenerator:
  - name: mlflow-values
    files:
      - mlflow-values.yaml=values.yaml
      - nginx-values.yaml=nginx-values.yaml
generatorOptions:
  disableNameSuffixHash: true
