---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mlflow
  namespace: default
spec:
  install:
    remediation:
      retries: -1
  releaseName: mlflow
  chart:
    spec:
      chart: mlflow
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 10m0s
  # https://github.com/bitnami/charts/blob/master/bitnami/mlflow/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: mlflow-values
      valuesKey: mlflow-values.yaml
    - kind: Secret
      name: mlflow-secrets
      valuesKey: MLFLOW_TRACKING_USERNAME
      targetPath: tracking.auth.username
    - kind: Secret
      name: mlflow-secrets
      valuesKey: MLFLOW_TRACKING_PASSWORD
      targetPath: tracking.auth.password
    - kind: Secret
      name: postgres-secrets
      valuesKey: POSTGRES_DB_USERNAME
      targetPath: postgresql.auth.username
    - kind: Secret
      name: postgres-secrets
      valuesKey: POSTGRES_DB_PASSWORD
      targetPath: postgresql.auth.password
