image:
  debug: true
tracking:
  auth:
    enabled: true
  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
  ingress:
    enabled: false
    hostname: dc-mlops.co.uk
    ingressClassName: alb
    path: /*
    tls: true
    extraPaths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: mlflow-tracking
            port:
              name: http
  persistence:
    enabled: true
    storageClass: efs-sc
    accessModes:
      - ReadWriteMany
run:
  persistence:
    enabled: true
    storageClass: efs-sc
    accessModes:
      - ReadWriteMany
postgresql:
  enabled: true
  auth:
    database: bitnami_mlflow
  architecture: standalone
  persistence:
    enabled: true
    storageClass: gp2
  primary:
    service:
      ports:
        postgresql: 5432
minio:
  enabled: false
