apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - sources.yaml
  - nfs-ganesha
  - minio
  - prediction-service
configMapGenerator:
  - name: env-values
    files:
      - nfs-values.yaml=nfs-ganesha/values.yaml
      - minio-values.yaml=minio/values.yaml
      - prediction-values.yaml=prediction-service/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true