apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - sources.yaml
  - nfs-ganesha
configMapGenerator:
  - name: env-values
    files:
      - nfs-values.yaml=nfs-ganesha/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true