---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
  namespace: default
spec:
  install:
    remediation:
      retries: -1
  releaseName: minio
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 14.6.32
  interval: 10m0s
  # Default values
  # https://github.com/bitnami/charts/blob/9515ca9f613593356857fbe18c4cbff43d87d285/bitnami/minio/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: env-values
      valuesKey: minio-values.yaml