apiVersion: v1
kind: Secret
metadata:
  name: s3-access-credentials
  annotations:
     serving.kserve.io/s3-endpoint: mlflow-minio
     serving.kserve.io/s3-usehttps: "0"
     serving.kserve.io/s3-useanoncredential: "false"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: admin
  AWS_SECRET_ACCESS_KEY: password