defaultBuckets: "artifacts"
service:
  type: ClusterIP
  loadBalancerIP: ""
  ports:
    api: 80
provisioning:
  enabled: true
  extraCommands: ["mc anonymous set download provisioning/mlflow"]
auth:
  rootUser: admin
  rootPassword: admin