defaultBuckets: "artifacts"
service:
  type: ClusterIP
  loadBalancerIP: ""
  ports:
    api: 80
provisioning:
  enabled: true
  extraCommands: ["mc anonymous set download provisioning/mlflow"]
auth:
  rootUser: admin
  rootPassword: admin
readinessProbe:
  enabled: true
  initialDelaySeconds: 300
  periodSeconds: 20
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 6
  httpGet:
    path: /minio/health/ready
    port: 9000
