---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prediction-service
resources:
  - certificate.yaml
  - release.yaml
  - release-nginx.yaml
  - source.yaml
configMapGenerator:
  - name: prediction-values
    files:
      - prediction-values.yaml=values.yaml
      - nginx-values.yaml=nginx-values.yaml
generatorOptions:
  disableNameSuffixHash: true
