serviceAccount:
  annotations:
    kubernetes.io/service-account.namespace: prediction-service
  name: prediction-service-sa
postgresql:
  primary:
    persistence:
      enabled: true
      storageClass: gp2
ingress:
  enabled: true
  className: nginx-prediction-service
  hosts:
    - host: predict.dc-mlops.co.uk
      paths:
        - path: /predict
          pathType: Prefix
        - path: /data
          pathType: Prefix
        - path: /swagger
          pathType: Prefix
        - path: /openapi.json
          pathType: Prefix
