modelPredictionEndpoint: http://house-price-predictor.kserve.svc.cluster.local/v2/models/house_price_prediction_prod/infer
postgresql:
  primary:
    persistence:
      enabled: true
      storageClass: gp2
image:
  tag: v3.0.1
ingress:
  enabled: true
  className: nginx-prediction-service
  hosts:
    - host: predict.dc-mlops.co.uk
      paths:
        - path: /predict
          pathType: Prefix
        - path: /data
          pathType: Prefix
        - path: /swagger
          pathType: Prefix
        - path: /openapi.json
          pathType: Prefix
