apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-letsencrypt
  namespace: cert-manager
  annotation:
    eks.amazonaws.com/role-arn: arn:aws:iam::058264114863:role/cert-manager-requests
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-letsencrypt-tokenrequest
  namespace: cert-manager
rules:
  - apiGroups: ['']
    resources: ['serviceaccounts/token']
    resourceNames: ['cert-manager-letsencrypt']
    verbs: ['create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-letsencrypt-tokenrequest
  namespace: cert-manager
subjects:
  - kind: ServiceAccount
    name: cert-manager-letsencrypt
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-letsencrypt-tokenrequest
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: opensource@digicatapult.org.uk
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector:
        dnsNames:
        - dc-mlops.co.uk
      dns01:
        route53:
          region: eu-west-2
          role: arn:aws:iam::058264114863:role/cert-manager-requests
