apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: opensource@digicatapult.org.uk
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selectors:
      - dc-mlops.co.uk
      dns01:
        route53:
          region: eu-west-2
          accessKeyIDSecretRef:
            name: digicat-mlops
            key: aws_access_key_id
          secretAccessKeySecretRef:
            name: digicat-mlops
            key: aws_secret_access_key
