apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: issuer-sync
  namespace: cert-manager
spec:
  interval: 1m
  path: ./flux/clusters/bridgeai-prod/cert-manager/cert-issuers/
  prune: true
  dependsOn:
    - name: cert-manager-sync
      namespace: cert-manager
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: CustomResourceDefinition
      name: challenges.acme.cert-manager.io
    - apiVersion: cert-manager.io/v1
      kind: CustomResourceDefinition
      name: orders.acme.cert-manager.io
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
