---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  install:
    remediation:
      retries: 10
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: "${cert_manager_version}"
  interval: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
      valuesKey: cert-manager-values.yaml
