apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - airflow
  - mlflow
  - nginx
  - kserve
  - sources.yaml

configMapGenerator:
  - name: shared-values
    files:
      - airflow-values.yaml=airflow/values.yaml
      - mlflow-values.yaml=mlflow/values.yaml
      - nginx-values.yaml=nginx/values.yaml
      - kserve-values.yaml=kserve/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true