apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - airflow
  - mlflow
  - nginx
#  - kserve-crd
#  - kserve-resources
  - sources.yaml

configMapGenerator:
  - name: shared-values
    files:
      - airflow-values.yaml=airflow/values.yaml
      - mlflow-values.yaml=mlflow/values.yaml
#      - kserve-crd-values.yaml=kserve/kserve-crd/values.yaml
#      - kserve-resources-values.yaml=kserve/kserve-resources/values.yaml
      - nginx-values.yaml=nginx/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true