---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: default
spec:
  interval: 10m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: apache-airflow
  namespace: default
spec:
  interval: 10m0s
  url: https://airflow-helm.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kserve
  namespace: default
spec:
  type: oci
  interval: 10m0s
  url: oci://ghcr.io/kserve/charts
  secretRef:
      name: ghcr-io
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: digicatapult
  namespace: default
spec:
  interval: 10m
  url: https://digicatapult.github.io/helm-charts
