---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - release.yaml
  - regression-model-training-config.yaml
  - regression-model-data-ingestion-config.yaml
