apiVersion: v1
kind: ConfigMap
metadata:
  name: drift-monitoring-configmap
  namespace: default
data:
  config.yaml: |-
    model_endpoint: http://localhost:5001/invocations   # model prediction endpoint
    data_repo: repo-path    # data repository url
    repo_branch: data-branch-name   # the branch name in the data repo where versioned data are kept
    historical_data_version: v1.0.0    # historical data version from the above repo
    new_data_version: v1.1.0    # new data version from the above repo
    feature_columns: ["mainroad", "guestroom", "basement", "hotwaterheating",
                           "airconditioning", "prefarea", "furnishingstatus",
                           "area", "bedrooms", "bathrooms", "stories", "parking"]   # feature columns to be used form the data
    label_column: "price"   # label column name
    report_location: "s3"   # where to save the evidently report
    report_name: evidently_report.html    # evidently report file name
    current_data_local_path: ../artefacts/HousingData.csv   # local path where the pulled current data is kept
    new_data_local_path: ../artefacts/HousingData-new.csv   # local path where the pulled new data is kept
    dvc:
      git_repo_url: "https://github.com/digicatapult/bridgeAI-regression-model-data-ingestion.git"  # The repo where the data is present
      git_branch: "feature/testing"   # The branch where the tagged data is available
      data_path: "./artefacts"   # Path of the data splits dvc files
      dvc_remote: "s3://artifacts"   # remote s3 bucket path for dvc to push and store data
      dvc_remote_name: "regression-model-remote"    # a name assigned to the remote
      dvc_endpoint_url: "http://minio"  # dvc endpoint url
      dvc_region: "us-east-1"    # dvc region - used for s3, just a placeholder for minio