---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kserve-resources
  namespace: default
spec:
  install:
    remediation:
      retries: -1
  releaseName: kserve-resources
  chart:
    spec:
      chart: kserve-resources
      sourceRef:
        kind: HelmRepository
        name: kserve
      version: "${kserve_version}"
  interval: 10m0s