apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow
resources:
  - certificate.yaml
  - source.yaml
  - data-ingest-configmap.yaml
  - drift-monitoring-configmap.yaml
  - model-training-configmap.yaml
  - release.yaml
  - release-nginx.yaml
  - volumes.yaml
configMapGenerator:
  - name: airflow-values
    files:
      - airflow-values.yaml=values.yaml
      - nginx-values.yaml=nginx-values.yaml
generatorOptions:
  disableNameSuffixHash: true
