---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  install:
    remediation:
      retries: -1
  releaseName: airflow
  chart:
    spec:
      chart: airflow
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
      version: "${airflow_version}"
  interval: 10m0s
  # Default values
  # https://github.com/airflow-helm/charts/blob/main/charts/airflow/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: airflow-values
      valuesKey: airflow-values.yaml
    - kind: Secret
      name: airflow-fernet-key
      valuesKey: value
      targetPath: fernetKey
    - kind: Secret
      name: airflow-webserver-secret-key
      valuesKey: value
      targetPath: webserverSecretKey
    - kind: Secret
      name: "airflow-postgres-admin-credentials"
      valuesKey: password
      targetPath: postgresql.postgresqlPassword
    - kind: Secret
      name: "airflow-admin-credentials"
      valuesKey: password
      targetPath: airflow.users.[0].password
    - kind: Secret
      name: airflow-prod-user-credentials
      valuesKey: password
      targetPath: airflow.users.[1].password
