---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: airflow
spec:
  install:
    remediation:
      retries: -1
  releaseName: nginx
  chart:
    spec:
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: "${nginx_version}"
  interval: 10m0s
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: airflow-values
      valuesKey: nginx-values.yaml
