apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shared-sync
  namespace: flux-system
spec:
  interval: 5m
  path: ./flux/shared
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      airflow_version: "8.9.0"
      nginx_ingress_controller_version: "11.3.13"
      mlflow_version: "1.4.18"