tracking:
  extraArgs:
    - --static-prefix=/mlflow
  auth:
    enabled: true
    username: admin
    password: password
  ingress:
    enabled: true
    hostname: localhost
    path: /mlflow
    ingressClassName: nginx
    extraPaths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: mlflow-tracking
            port:
              name: http
  service:
    type: ClusterIP
minio:
  auth:
    rootUser: admin
    rootPassword: password
  extraEnvVars:
    - name: MINIO_BROWSER_LOGIN_ANIMATION
      value: "off"