tracking:
  auth:
    enabled: false
    password: password
  ingress:
    enabled: true
    hostname: localhost
    path: /mlflow
    ingressClassName: nginx
postgresql:
  auth:
    password: password