tracking:
  extraArgs:
    - --static-prefix=/mlflow
  customReadinessProbe:
    failureThreshold: 5
    httpGet:
      path: /mlflow
      port: http
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  auth:
    enabled: false
  ingress:
    enabled: true
    hostname: localhost
    path: /mlflow
    ingressClassName: nginx
    extraPaths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: mlflow-tracking
            port:
              name: http
  service:
    type: ClusterIP