tracking:
  extraArgs:
    - --static-prefix /mlflow
  auth:
    enabled: false
  ingress:
    enabled: true
    hostname: localhost
    path: /mlflow
    ingressClassName: nginx
  service:
    type: ClusterIP