serviceAccount:
  annotations:
    kubernetes.io/service-account.namespace: default
  name: prediction-service-sa
postgresql:
  auth:
    password: password
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: localhost
      paths:
        - path: /predict
          pathType: Prefix
        - path: /data
          pathType: Prefix
        - path: /swagger
          pathType: Prefix
        - path: /openapi.json
          pathType: Prefix
