apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Y3NeGgfeggxhbF1WO86JfDps9ABusbs/QzmY7LDubnNum80glH/GEBczOlG+MwSaBBvqamQtsububxkxHPd4v7ObfpxQaK3LU3EoX6Staj7d9UVyHbEadAeQx2GIo6o3neHX3P3LOjIP4EW87l0izHkqtQvr54KMx6J9sOJmUN0zIxMnnMe02k7eu8c/vwbhe5sXvDHr37vvQF/K2BPAZYWyzU7jIbw9X3l9KALTkYzbsRIlspsho32QJ1Xe/lhhyDlx5CIizyaRqKlfrKzBzuzteO5V5F0oj6vdnT9aKvl9z5S2AePwJj0znI5nF7IaYRQC++kvzN3uI1kI+BMqhkDdBzOaVUPH+2x5EH75KAX9tCO3pJlnjnYKObOAXlnyqtcc86vh9Gl79sulLlNlzI/8DXBSqVpkm0J5hhEh1fkwDHeLQiMkefWpGj2r+tLpr7mOFqMYtN2CxDc+lbm/Oyic9guoklLBEHbWUIsN0OgrYKob,iv:BCdK2HP52HwaAodP7lvQg2X+E0FNPc2UOPuBFMpW31U=,tag:DIFpLjUKsHofmqCrSXOmkg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghcr-io
    namespace: airflow
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-15T16:35:13Z"
    mac: ENC[AES256_GCM,data:0rutrNzRRE4r0UFoObqsTA/ah6lLk1Bs6Pam5VwCt60u8AjCMSymqbgYYkYxcVjPgfQ7+lLOBjavULXj3VmgesgnwE34bR26InkoycWZZPltn34PBWHy84lxuHTCsn7vbf24gzI5neW4U1+hFs9t54hOe2fgQ2z7FS7xs1iOuEk=,iv:jnbhKSkYdV482NLDO3YVHfwky/glkHr6O1tVns8nEj8=,tag:/DgXRtb9+o0cmCzhyzN1TA==,type:str]
    pgp:
        - created_at: "2025-01-15T16:35:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0/EQbQcE5PUARAAj3R/0933k7R2SztsnNbA6dVsbQdP0T7KtD4gS6He8m2C
            5F8srGBuWUcJ3gCUumWsXec5bV+9M4vDIFCD1g74BK6MsiuJuzGiYVoD0fn34H3w
            nO5h6agq5YV9U83SfY6xV9XxuiyE5Q5emtdRLXktmNZotPwBnspGOi/ZtANXf9af
            kvqOMreYEDg3CR8oVgS282HKNn4a0klSvnr1FGqMAEOMbQtQlA51ECrKR+2Nb2dX
            5VRiGO0W7MGrR8EyE63WEibM32Rrg9zePY/lfPiijstqAzH60VymDxbUy0p7b37T
            FMh3NJZGYnAstLqfxtAKS8llHyghfYCqV5r3xmVvxZEhdI2hDlI9HVCColkQ2K+v
            huijXsoohUiu1MLnHxQPbsVITUk5wMay88+Hbyz7jrNiqa6QAa9TLKtm2g3J+f5L
            60/F1QhIyFlcsep0i4mGsufWpbB270dgfhie8Mw3cEf/6NAtMRY2SkWqdSsQxH2Q
            SuPUlYNKpW4NZ9U4r542OkqvcZkIz1GUd+c0d9SNfS6EVr4Qz8DKRlaurcmZTHeY
            khfYx8i3yMawUOE+1ToQJt6cBS1dnNup093PXm88n7ZcG8626bX13m5dKsyT2lnh
            F0pxggKdG3Qz+yrCGSwmOGwT1cW95Hl6lfAExQrpkK4NI6I0kz4udNgsaPr2BKjU
            aAEJAhBiruyVS2+0D+Amzm5cPsf+DzqIqqSY5HP3OQfBXAwKJ7mN7VcjBcoi3T7R
            L1mUDfGqmi0mbbZMhyEKbEus7XJA2lDJTub8hTcUBUv5mMQ04xtIOXlP3k5nTLNd
            xO1pli3MZewa
            =09+N
            -----END PGP MESSAGE-----
          fp: 2B78BF99642CE90A7ACF9284C13A02BF95797BCD
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
