apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:YZkULPgnhjJTh2d+WpgZ/1Ag81xWfgMYVTa+9j0oLuQlHC+vsf3T2a90eaojsP61HbX0qT4OvSrKmam4kYR9AoKwaRQgWGZm6+BZDHGyzTNdLwALkhSSXPJukMdLlZ5wWDxTPK5WHyrZ9gslTZ+ulx9+1n4aCUO2FoT+6gi+/iniuUzSZc4x37ayHHDVb1+S6hadhnvJoNDh9hHCZfRVcyoMpxr9JZMWW8XK9cwLRK+Cyj+HHfiXEa6ekqlLpYitcmzmgvcCa/t8VXurDO54XMBoep3qRifQOf7w5YoBYBpk+rfVFp81zE1323nlt9sXP03VnQ==,iv:53rshwAO4HChS0bqddg2tAO9RFmkBRhh9ldjmUSEK3g=,tag:1ISZPZ/76f6ZTb4W3BsXdQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghcr-io
    namespace: kserve
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-15T13:23:22Z"
    mac: ENC[AES256_GCM,data:NfMdU7hWO268/1iHEtc/YE+pRdjMuHwXbzJAsHLgXjdx4i10ytr+ir59VamjQip2Jj22Mt0VNEsSXZNVXvvG/jqIGS9ZdiO3CmL0+KTQQpsRJfSbDBut5rD2g26J2ZkRZVxW+aVv0QlRdvQzmDv5VVPcZhFu8wy2hlZ0SXyMBIo=,iv:8zmu0RtNISTDbLTthyzzoIFcinWTdp1n0d29Nd/Vsvg=,tag:nSCCv2Bu4gmXO2XZ7wPJFQ==,type:str]
    pgp:
        - created_at: "2025-01-15T13:23:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0/EQbQcE5PUARAAnpUKwj/tPMvL3QQ4sytS+qzh20D8sSdZZi3PjQUL/UQQ
            2IVzEENvYi5cFSCDvRmEo403xsfGV9YLIOURAwiNb35bqo5yWr40INLJDMJyT+mg
            djvPNb4+oTqnIT0DsyQXtPvubR5pZwj78zGzdE9XgFy8Xx/MI7D5tLXnIHdFDged
            p30+4h2oBEnUBudFBAd8/wvza6GfriN7I8Sx7i5PY1g2ASFjQjlEInAKsiAgBaeM
            oYcTuMfS79VA1jYbNfPWOFywYLFRdCe3zRl4B8dF0SIiyFVfOmYOQqaBLCp+J0Xq
            mJQnUvoucBUCN9wIxC1veCoZpeSO/Kydz7kQ2mpbg2aN5yl0o4HmfRNvo4MbiFNI
            MzUkYawAZ3o34hVHuCAQbP+i4tmk2e+Q2zOOKrFbTvogTtPt8zy8ov50mtI8a+VN
            AXTpq4vPzzkARwVdUYkk+Hkw1EFo8z9w40gfx67reXclZWGp0FQq6jfnxI6HIXj+
            onRZn8zvRgP8TAl7SelIxCg+kMIQxM17QDYixwdr3U+VXZHRHkVG4kN5X/Qhaloh
            5/chqMhjmQwyZhDNHZ5x8kn6P2HTNYYX7vyX4mqGyhMyDDcwznGAeaFPKcNCuNbG
            SyhBIK6qkCuGSucfWMXlikWoPm37wVI1uzjzpQ4G2A3wWrsXaVEGcI24bb1t1HDU
            aAEJAhBUw/MMZ6legPZcFFitZ7SORfYlq/JrQ/Sknt64JS5bk/gCNj/4zcnxLoLv
            mjYL5pKM56r0ftti0py5zlqqiTRZ4cfIfEi/sEj9ime/MuqmLu4jAHE30Fa+tHuN
            MjKRnjX5XAcE
            =QYhs
            -----END PGP MESSAGE-----
          fp: 2B78BF99642CE90A7ACF9284C13A02BF95797BCD
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
