apiVersion: v1
data:
    password: ENC[AES256_GCM,data:lf3mZVlk74ImpCM9KpQf/euh5bTI2oY4jpdV/JdAX/8=,iv:oiPPYxX21IORjdJM5btkhKOTK0c/jN83nPZ6MfawZKM=,tag:WqmauqnK1ObHnNFep1sM8Q==,type:str]
    username: ENC[AES256_GCM,data:bQUC8LBkP98=,iv:r4/DMz34FycKYkOgBwQ8ZpAPQcuTie0r8a3OfC5o7ig=,tag:YuXV3sRqjCP8smOxx4FQnw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mlflow-postgres-admin-credentials
    namespace: mlflow
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-22T10:45:37Z"
    mac: ENC[AES256_GCM,data:lsZESuncrI4QcfbTHGPh9PiIcMWoh8lFVnJOhxwHdcUiRZhdgnnY1ky/T7vLK115Ae7h+T3cnTLVlkcHmeyO1EoUwvIZIwc7T20MHX73ETglmtlLX8qtXWByOyi27bY1Ry9aIGcsBXvbXHXm9bJTnjk2bmLkLJ8Db2ZX4ljWagw=,iv:9BcQGDRzLIR2709HmoNfEsY26VEkaWG8sUFoZwFemT0=,tag:iQjQGN04IuSXk6DXuqd65g==,type:str]
    pgp:
        - created_at: "2024-08-22T10:45:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0/EQbQcE5PUARAArXXZgZG2C7X2AqWePFgaqiEnh7i0TZqSGrrDTPI5K4tY
            Qyh0GpKiYKIG/WjU+rWm2TMQPaIla9bgOZVLR6xMy32F2VlU6eKxxDjbIThrZbl6
            DTtmNfO0/YA8sspEMb3EBUofEkOiJNPsYx5rOaWqC+ptZfA6kG1CM1QhbA9R2BI+
            mfarxOaxPXM+I3IYOVkhx7/GcCeNFWVvp0B0H4/hL98wpayZreNkSyXNSFY1g/4T
            Wd1sBO0bw7HGpAbQq4uFvKb/HlIM8rpvORJQcF+xYJk+svs9wQos7vLvrpwpS3UM
            nPVn97nvDfgWpUzNcMDwVvYBFzrBfHNUUtJh0Z8YO6YuCWSek2EMGfhyOWKPMnu7
            ne8vl6VDcAr6dTBtr5ImopdJ+VTbBblRuRILejALGm0sUMwPUBxoE1LfZ1GK5bVI
            3sTgHilG+lGBNjB5PxzIDVsiKYdQTj284IRAHXmqnNlH7wpC0vIsT58Vy2I93V3R
            qUiSy7/4FQ3KOtxjcU5IkhiSfNbLBRndiTyfBFvgpo3VmsO9c4RWSs9nMDvgu2IU
            H4pcVV3C/KgcupkMTgunKmRjbHWA7cTHgZ0gnVZhV6WaCvYSFkjWP9ML9bwgXZtE
            r8xkgtATLaMTCQ3qIP2PUIMNysCehRDSqz707CVznphc0VR5y+Mbqf390VfMJiTU
            aAEJAhCt+pD3mRNEyNYk90+HKok1DPLPHUz8lFIPLL8VFqk9Bb0h1i45+CTHDjZY
            ADqfOzFoE8Y97o/NcvqRaFQYqZGAbCqvNTcWCr1V4SYDxfXeCTjbEFpF8QaG7eUb
            ySXtAcwrvN8g
            =Ll0U
            -----END PGP MESSAGE-----
          fp: 2B78BF99642CE90A7ACF9284C13A02BF95797BCD
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
