apiVersion: v1
data:
    test: ENC[AES256_GCM,data:rP0rrYFgZVs=,iv:SMnjiLgrVv0E23DlrovZn5TpmYXakz8KLjc4mLdJqZ4=,tag:GvqfIW3djJf0z3ylZmTkHg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-05T09:30:44Z"
    mac: ENC[AES256_GCM,data:A/S43kYNVRQvaZNqDOFjdDZhEkAxYuY0rqUczbOm2R5bB/Yx+RzdhlU0eUfjJlikgXYivu9Ig2l0u8d0a318QyniGOQ7aKvEREVo4mjUoMEa+RS8X56CP3WLKWK/jUrlF3wRPJNhM1L0upsxOtJVkHXr7sBILFIgsVOCYBzUbb8=,iv:8Wbl1DGGekHcKht8KoDRWOIpmBEYcFYLC39mSKcrxWY=,tag:91r7Q/i33gyqQQipB0N/8g==,type:str]
    pgp:
        - created_at: "2024-08-05T09:30:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0/EQbQcE5PUAQ/8DqrxVC196vw4kDH32/xjYLBKIf+lo8QG89HTtkyt0kOM
            osZPvCS4m/P7BHUQJGy3I/0dIyjvc5SClaPZWzN5KCDwFDy6LrrbDBbLPKBgv+I3
            ImHCF0ikpuNyGA8Nb69W/06cVDcLu1czfSBTwmpTnLDUdDQgzTg0/f8FHCLZGI8A
            mMThRPPMBprJbBIVD7djNEM5YbmAS8zYoJ/AnMaP+P86K3qddS3pKtS7kyOJX70D
            5T3heESbTVySVpi9bRR8Dmr0ng+nAqLzav6HQWi3LTrsiEm9UkLAbyjVbfPDuPQ9
            UX8UIk5cxxiC7qC7Moakognol2u6NRYK4XYtmJ5ONFHctaJqpzxfwyakrz7AJRiN
            hBeyrTHrwkEZNBVMuwzA/mMEtiM2/BUf0oDKmISAm2gWFLL8n/MAvWvUZR8IqYyU
            UUIbF9J04h/MeJrfMyUqdEcI6nW5153h4/mMQ011zEkKS3I9j8Yuj51u4JuSQpaW
            BxqOhZmmKNmQKTL+nmRQ3UmBww3vDb9mA+cDT2H87Z/iAqARFEbc/vUKYO+z0c5B
            HGCFJkxhjZfx2QA4qgTcWJqzt+gyMxsWBKFSA62qHCCNA2LLbLnuLGHycEJLMsrH
            EuxNnPIO5e2Ctf4KW6QwU1um4N9dBPSXaTnrLsWxAfLVYaidVWHoLLdmTw97l73U
            aAEJAhAbp7P6a1umsaNftGJLjsF6tbzCS1Ma9B3R9vNyCW+P10bXkhcRJtNYFx5I
            CtaYWhiaxxnTuvn+Jn0+XVWrptrJce4K4E5Pe0L4sdp5r/FKAw4FDGItlie2BnLG
            XPy2UZidLsRN
            =PXE5
            -----END PGP MESSAGE-----
          fp: 2B78BF99642CE90A7ACF9284C13A02BF95797BCD
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
