---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mlflow
  namespace: default
spec:
  install:
    remediation:
      retries: -1
  releaseName: mlflow
  chart:
    spec:
      chart: mlflow
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: "${mlflow_version}"
  interval: 10m0s
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/mlflow/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: shared-values
      valuesKey: mlflow-values.yaml
    - kind: ConfigMap
      name: shared-env-values
      valuesKey: mlflow-values.yaml