---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-sync
  namespace: cert-manager
spec:
  interval: 1m
  path: ./flux/clusters/bridgeai-prod/cert-manager
  prune: true
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: certificates.cert-manager.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: issuers.cert-manager.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusterissuers.cert-manager.io
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mlflow-sync
  namespace: mlflow
spec:
  interval: 1m
  path: ./flux/clusters/bridgeai-prod/mlflow
  prune: true
  # healthChecks: TODO
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kserve-sync
  namespace: kserve
spec:
  interval: 1m
  path: ./flux/clusters/bridgeai-prod/kserve
  prune: true
  # healthChecks: TODO
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      kserve_version: "v0.13.1"
